name: konfa
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.0
  flutter: 3.29.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  streaming_sound:
    git:
      url: https://github.com/royalcat/streaming_sound.git
      ref: 5de8f1c42b15a263c81e1583d8df8be8fdc0fdc5
  protobuf: ^4.0.0
  grpc: ^4.0.1
  opus_dart: ^3.0.1
  rxdart: ^0.28.0
  permission_handler: ^12.0.0+1
  l: ^5.0.0
  provider: ^6.1.2
  very_good_infinite_list: ^0.9.0
  fixnum: ^1.1.1
  dynamic_color: ^1.7.0
  openid_client: ^0.4.8
  url_launcher: ^6.3.1
  opus_flutter_android: ^3.0.1
  opus_flutter_ios: ^3.0.1
  isolate_generator_annotation: ^0.0.6+1
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  meta: ^1.16.0
  go_router: ^15.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  protoc_plugin: ^22.0.1
  go_router_builder: ^2.9.0
  build_verify: ^3.1.0
  # isolate_generator:
  #   path: ../isolate_generator

flutter:
  uses-material-design: true

  # TODO split between android and ios
  assets:
    - assets/opus/linux/libopus.so
    - assets/opus/windows/libopus_x64.dll
    - assets/opus/license.txt
