// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VoiceConnectionManager>>
abstract class VoiceConnectionManager implements RustOpaqueInterface {
  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<VoiceConnectionManager> newInstance({
    required String relayAddress,
  }) => RustLib.instance.api.crateApiVoiceVoiceConnectionManagerNew(
    relayAddress: relayAddress,
  );

  Future<void> voiceJoin({
    required String serverId,
    required String channelId,
    required String userId,
  });

  Future<void> voiceLeave();
}
